# Generated by Django 4.2.5 on 2023-11-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Search_Console',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clicks', models.IntegerField()),
                ('impressions', models.IntegerField()),
                ('site', models.URLField()),
                ('ctr', models.FloatField()),
                ('position', models.IntegerField()),
                ('query', models.CharField(max_length=255)),
            ],
        ),
    ]
