name: Deploy-to-AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

      - name: Get Github IP
        id: ip
        run: |
          response=$(curl -s icanhazip.com)
          echo "ipv4='$response'" >> "$GITHUB_OUTPUT"

      - name: Allow Github IP to AWS
        run: |
            aws ec2 authorize-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32

      - name: Checkout the files
        uses: actions/checkout@v3

      - name: Deploy to AWS
        uses: easingthemes/ssh-deploy@main
        with:
            SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
            REMOTE_HOST: ${{ secrets.HOST_DNS }}
            REMOTE_USER: ${{ secrets.USERNAME }}
            TARGET: ${{ secrets.TARGET_DIR }}
            EXCLUDE: "/.git/, /.vscode/"
            SCRIPT_BEFORE: ls
            SCRIPT_AFTER: |
                sh /home/ubuntu/gsc-api/scripts/deploy.sh

      - name: Remove IP from AWS
        run: |
            aws ec2 revoke-security-group-ingress --group-id ${{ secrets.AWS_SG_ID }} --protocol tcp --port 22 --cidr ${{ steps.ip.outputs.ipv4 }}/32





